newt upgrade: Fix repo conflict error message
If a `newt upgrade` operation fails due to conflicting repo
requirements, the error message should indicate which requirements are
in conflict.  The bug was that the error message was missing "root
requirements" (requirements specified in project.yml), so the message
was incomplete.

For example (before fix):

    Error: Repository conflicts:
        Installation of repo "mynewt-dummy-repo-04" is blocked:
            mynewt-dummy-repo-01,1.0.0 requires mynewt-dummy-repo-04 ==1.0.0

After fix:

    Error: Repository conflicts:
        Installation of repo "mynewt-dummy-repo-04" is blocked:
                           project.yml requires mynewt-dummy-repo-04 ==1.0.2/0eaf06337c8f8dc8c49fffa884a6a0c2fb223d73
            mynewt-dummy-repo-01,1.0.0 requires mynewt-dummy-repo-04 ==1.0.0