logcfg: Allow logs to be defined in `syscfg.yml`
A package can define logs in its `syscfg.yml` file under the heading of
`syscfg.logs`.  During the build process, newt generates a C header file
called `logcfg/logcfg.h` containing macros for using each generated log.

Each entry in the `syscfg.logs` map has the following structure:

        <log-name>:
            module: <module>
            level: <level>
            guest: <true/false> (optional)

For example:

    syscfg.logs:
        MY_LOG:
            module: MYNEWT_VAL(MY_LOG_MODULE)
            level: MYNEWT_VAL(MY_LOG_LEVEL)

It is recommended, though not required, that the module and level fields
refer to syscfg settings, as above.  This allows the target to
reconfigure a package's log without modifying the package itself.

The above log definition generates the following code in
`logcfg/logcfg.h` (assuming `MY_LOG_MODULE is set to LOG_LEVEL_ERROR (3)):

    #define MY_LOG_DEBUG(logcfg_lvl_, ...) IGNORE(__VA_ARGS__)
    #define MY_LOG_INFO(logcfg_lvl_, ...) IGNORE(__VA_ARGS__)
    #define MY_LOG_WARN(logcfg_lvl_, ...) IGNORE(__VA_ARGS__)
    #define MY_LOG_ERROR(logcfg_lvl_, ...) MODLOG_ ## logcfg_lvl_(MYNEWT_VAL(MY_LOG_MODULE), __VA_ARGS__)
    #define MY_LOG_CRITICAL(logcfg_lvl_, ...) MODLOG_ ## logcfg_lvl_(MYNEWT_VAL(MY_LOG_MODULE), __VA_ARGS__)

If two or more logs have module values that resolve to the same number,
newt aborts the build with an error:

    Error: Log module conflicts detected:
        Module=100 Log=MY_LOG Package=sys/coredump
        Module=100 Log=YOUR_LOG Package=sys/coredump

    Resolve the problem by assigning unique module IDs to each log,
    or by setting the "guest" flag of all but one.

The "guest" flag, when set, allows a log to use the same module as
another without generating an error.