Resolve transient packages before dep resolution
This fixes #286.

If a split image specifies a transient package as the loader, newt will
fail to build it.

For example, in this target:

    target.app: "@apache-mynewt-core/apps/splitty"
    target.bsp: "@apache-mynewt-core/hw/bsp/nordic_pca10040"
    target.build_profile: optimized
    target.loader: "@apache-mynewt-core/apps/bleprph"

`@apache-mynewt-core/apps/bleprph` is a transient package; it links to
`@apache-mynewt-nimble/apps/bleprph`.

Newt reports the following error when asked to build this target:

    Error: Two app packages in build: apps/splitty, apps/bleprph

The bug occurs when newt tries to partition the master set of packages
among the loader and app.  In a split image, all loader packages are
shared among both loader and app, so the app automatically pulls in all
the packages in the loader *with one exception*: The loader's "app"
package (confusing terminology) does not get pulled in.  The app has
its own "app" package; it doesn't need the loader's "app" package.

The problem was that newt couldn't identify the loader's "app" package
if it was transient.  This package's type was "transient" (not "app"),
so it got pulled in to the app.  Consequently, the app contained two
"app" packages, resulting in the error.

The fix is to resolve transient packages among seed packages before
performing dependency resolution.  With this change, the loader's "app"
package is identifiable when newt decides which packages get pulled in
to the app.