Remember which packages satisfy API requirements
This is a fix for an error reporting bug.  When any API requirement was
unsatisfied, newt would report all APIs as unsatisfied.

For example, mynewt-blinky at commit
06536d2a86a4eaf8d619fe2bad75a4cdf9b77cc8 is broken.  The blinky app has
an unsatisfied `log` dependency.  When I try building it, I get the
following error:

    Error: Unsatisfied APIs detected:
        * console, required by: hw/mcu/native, kernel/os
        * log, required by: sys/log/modlog

The `console` API is satisfied, so it should not be reported.

This newt bug was introduced in
a2573a97549cc05dd4949ffca3f87165b239f8aa.  Prior to that commit, each
satisfied API dependency was tracked in two directions: the depender
remembers which package satisfies its API requirement, and the dependee
remembers who requires the API.  In the bad commit, the first of these
was accidentally removed.

The fix is to add the missing code back.  Now, the depender remembers
which packages satisfy its API requirements again.