Forced reinstall (`install -f`) was always failing
Forced reinstalls always failed with an error message similar to the
following:

    Error: Error updating "blehostd": chdir /Users/ccollins/tmp/myproj2/repos/blehostd: no such file or directory

The problem occurred when newt attempted to fetch the repo after
deleting the repo's directory.

The fix is to re-clone the repo rather than fetch it if the directory is
missing.