Use `util.MoveDir()` instead of `os.Rename()`
`os.Rename()` fails if the source and destination paths reside on
different disks.  The `util.MoveDir()` function handles both cases (same
disk and different disks).

Before this commit, a cross-disk rename might cause the newt command to
fail with an error like this:

    Error: rename /tmp/mynewt-user-pre-link391870512/src /home/me/repo/bin/targets/my_blinky_sim/user/pre_link/src: invalid cross-device link