newt - Fix error message for priority conflict.
The fields in the error message were misordered.

Example:

OLD:
Error: duplicate priority value: setting1=BLE_LL_PRIO setting2=MCU_UART_POLLER_PRIO pkg1=0 pkg2=net/nimble/controller value=hw/mcu/native

NEW:
Error: duplicate priority value: setting1=BLE_LL_PRIO setting2=MCU_UART_POLLER_PRIO pkg1=net/nimble/controller pkg2=hw/mcu/native value=0